version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"

sphinx:
  configuration: conf.py
  fail_on_warning: true

python:
  install:
    - method: pip
      path: .

formats:
  - pdf
  - epub

# vim: set sts=2 sw=2:
